f0 Двоичное дерево поиска
G-K-R-git/PY111-German pull request #15
Opened 2021-01-18 10:29 UTC by G-K-R-git

исходные тесты в этот раз совершенно бестолковые

2021-01-22 11:04 UTC, EnotYoyo commented on Tasks/f0_binary_search_tree.py
> +        node = node['right']
Проверьте, что эта операция у Вас меняет граф

2021-01-22 11:06 UTC, EnotYoyo commented on Tasks/f0_binary_search_tree.py
> +            remove_if_found(current_node)
Здесь не понял логигу.

2021-01-22 11:07 UTC, EnotYoyo requested changes
Проверьте удаление еще раз

2021-01-22 11:40 UTC, G-K-R-git commented on Tasks/f0_binary_search_tree.py
> +            remove_if_found(current_node)
если мы нашли нужный узел для удаления и у него оба потомка, то нужно перейти в его правую ветку. Если в правой ветке нет левой подветки, то мы рекурсивно удаляем этот правый узел. Если есть - ищем минимум из левых подветок

2021-01-22 11:51 UTC, EnotYoyo commented on Tasks/f0_binary_search_tree.py
> +            remove_if_found(current_node)
А почему собственно мы вызываем удаление для правого узла. То есть наша задача удалить node из дерева, а мы вызываем удаление для current_node, хотя в этом случае node не трогаем вообще

2021-01-22 11:52 UTC, EnotYoyo commented on Tasks/f0_binary_search_tree.py
> +            remove_if_found(current_node)
Во второй ветке понятно, мы нашли левую ноду в правом поддереве, *переместили ее* и удалил после. А тут не понимаю.

2021-01-22 13:47 UTC, G-K-R-git commented on Tasks/f0_binary_search_tree.py
> +            remove_if_found(current_node)
тут то же самое, но мы не можем просто удалить вот эту правую ноду если у неё есть левый потомок, потому что он должен будет встать на её место (ну или не он, а минимальный из левых, если их там много). А если левых потомков у неё не осталось - удаляем спокойно со всеми сдвигами, т.е. опять вызываем эту функцию

2021-01-22 13:57 UTC, EnotYoyo commented on Tasks/f0_binary_search_tree.py
> +    remove(50)
@G-K-R-git  Поменяйте тут на remove(81)

2021-01-23 07:52 UTC, EnotYoyo approved these changes
Теперь верю :) Принято

2021-01-23 08:13 UTC, merged